export {default as logo} from './logo.jpg';
export {default as shopping} from "./shopping.png";
export {default as mail} from "./email.png";
export {default as banner} from './banner.jpg';
export {default as ban} from "./ban_img.png";
export {default as shoe} from "./shoes.png";
export {default as underwear} from "./underwear.png";
export {default as pent} from "./pent.png";
export {default as shirt} from "./t_shart.png";
export {default as jakit} from "./jakit.png";
export {default as helbet} from "./helbet.png"
