export { default as HomePage} from "./Home";
export {default as NavBar} from "./NavBar";
export {default as AboutPage} from "./About";
export {default as ProductPage} from "./Products";
export {default as FashionPage} from "./Fashion";
export {default as NewsPage} from "./News";
export {default as ContactPage} from "./Contact";
export {default as Layout} from "./Layout";
export {default as SecNavBArPage} from "./SecNavBAr";
export {default as Footer} from "./Footer.jsx";